package dnspod

const (
	DefaultRecordLine = "默认"
	DefaultTTL        = 600
	DefaultWeight     = 100
	DefaultStatus     = "ENABLE"
	DefaultRemark     = "Automatically generated by ddns-go, please do not modify manually"
)
